baseURL = "https://bitapp.it/"
languageCode = "en-us"
title = "Bitapp Site"
theme = "hugo-bitapp-theme"

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Prodotti"
    url  = "/prodotti/"
    weight = 2

[[menu.main]]
    name = "Realizzazioni"
    url  = "/realizzazioni/"
    weight = 3


[[menu.main]]
    name = "Contatti"
    url  = "/contatti/"
    weight = 4



    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email

    email = "info@bitapp.it"

    about_us = "<p>...</p>"

    logo = "img/logo-bitapp.png"
    address = """<p><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>"""
    latitude = "44.515267"
    longitude = "11.373888"

[params]
    date_format = "2 Jan 2006"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true



[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.


[params.prodotti]
    enable = true
    title = "Prodotti"
    subtitle = "<p>...</p>"

[params.realizzazioni]
    enable = true
    title = "Realizzazioni"
    subtitle = "<p style=\"text-align:center;font-weight:bold\">Bitapp è il tuo Partner tecnologico per lo sviluppo di soluzioni innovative: <br />ottimizzare, semplificare e potenziare i processi aziendali,<br /> è la nostra Mission.</p> <p style=\"text-align:center;\">Un team di sviluppatori, esperti in applicazioni mobile, grafici e ingegneri, sono al tuo fianco per progettare insieme la soluzione più adatta alle tue esigenze di business. <br /><br /><b>Software gestionali, CRM evoluti, APP, E-commerce e le migliori tecnologie digitali integrabili con piattaforme e siti web.</b> <br />Soluzioni Web Based accessibili da mobile, pc o tablet.</p>"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Clienti"
    subtitle = ""
